# Generated by Django 2.2.6 on 2019-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
