# Generated by Django 2.2.6 on 2020-04-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
