# Generated by Django 2.2.6 on 2019-11-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20191102_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d'),
        ),
    ]
