# Generated by Django 2.2.6 on 2020-04-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200401_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
    ]
