# Generated by Django 2.2.6 on 2019-11-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20191107_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stillsgallery',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='movie.Movie'),
        ),
    ]
