# Generated by Django 2.2.6 on 2020-01-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20200116_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
