# Generated by Django 2.2.6 on 2020-01-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20200116_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='movie.CategoryGroup'),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
