# Generated by Django 2.2.6 on 2020-01-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20200116_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
    ]
