# Generated by Django 2.2.6 on 2020-01-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_category_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.DeleteModel(
            name='CategoryGroup',
        ),
    ]
