# Generated by Django 2.2.6 on 2020-01-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_remove_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.Category'),
        ),
    ]
