# Generated by Django 2.2.6 on 2020-01-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_movie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='', max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
