# Generated by Django 2.2.6 on 2020-01-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_videosource'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='movie_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
