# Generated by Django 2.2.6 on 2020-01-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_videosource_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_source',
            field=models.ManyToManyField(blank=True, related_name='video_source', to='movie.VideoSource'),
        ),
    ]
