# Generated by Django 2.2.6 on 2020-01-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_movie_video_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_source',
        ),
    ]
