# Generated by Django 2.2.6 on 2020-01-17 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_remove_movie_video_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosource',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie.Movie'),
        ),
    ]
