# Generated by Django 2.2.6 on 2020-01-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_auto_20200117_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.CharField(default='', max_length=300),
        ),
    ]
