# Generated by Django 2.2.6 on 2020-01-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_auto_20200118_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='star',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='nation',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
