# Generated by Django 2.2.6 on 2020-01-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_auto_20200118_0811'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='movie',
            index_together={('id',)},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
