# Generated by Django 2.2.6 on 2020-01-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_auto_20200128_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosource',
            old_name='movie_name',
            new_name='movie',
        ),
    ]
