# Generated by Django 2.2.6 on 2020-02-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_auto_20200131_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='body',
            new_name='content',
        ),
    ]
