# Generated by Django 2.2.6 on 2020-02-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0034_auto_20200202_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=''),
        ),
    ]
