# Generated by Django 2.2.6 on 2020-02-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0037_auto_20200205_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(max_length=100),
        ),
    ]
