# Generated by Django 2.2.6 on 2020-02-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0039_auto_20200205_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
