# Generated by Django 2.2.6 on 2020-02-06 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0040_auto_20200206_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('fans', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='fans', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='movie.Movie')),
            ],
            options={
                'unique_together': {('fans', 'movie')},
            },
        ),
    ]
