# Generated by Django 2.2.6 on 2020-02-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0041_moviefans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users_like',
        ),
    ]
