# Generated by Django 2.2.6 on 2020-01-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200118_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='content',
        ),
    ]
