# Generated by Django 2.2.6 on 2020-01-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20200119_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Draft'), ('2', 'Publish')], default='1', max_length=24),
        ),
    ]
