# Generated by Django 2.2.6 on 2020-01-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='content',
        ),
    ]
