# Generated by Django 2.2.6 on 2020-01-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
