# Generated by Django 2.2.6 on 2020-01-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_auto_20200122_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='active',
        ),
    ]
