# Generated by Django 2.2.6 on 2020-01-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_auto_20200123_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='active',
        ),
    ]
