# Generated by Django 2.2.6 on 2020-01-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_auto_20191130_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Hello World.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.CharField(blank=True, default='/cover.jpg', max_length=100),
        ),
    ]
