# Generated by Django 2.2.6 on 2020-01-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_auto_20200120_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.CharField(blank=True, default='/cover.png', max_length=100),
        ),
    ]
