# Generated by Django 2.2.6 on 2020-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0010_auto_20200120_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.CharField(default='https://i.imgur.com/1kZR1f9.jpg', max_length=300),
        ),
    ]
