# Generated by Django 2.2.6 on 2020-01-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0011_auto_20200122_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.CharField(blank=True, choices=[('unreviewed', 'unreviewed'), ('reviewing', 'reviewing'), ('reviewed', 'reviewed')], default='unreviewed', max_length=24),
        ),
    ]
