# Generated by Django 2.2.6 on 2020-01-28 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_profile', '0014_auto_20200128_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuser',
            name='follower',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='user',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together={('user', 'follower')},
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='follow',
        ),
    ]
